### ISSUE TITLE
bower install之后，页面访问报找不到libs下的资源

### ISSUE THREAD

**Issue by zhengzhiqiang** [eshengsky/iBlog#10]
bower install之后，页面访问报找不到libs下的资源，请问该怎么办？或者文档能否再详细说下？比如安装bower是npm install -g bower之类的？

**Comment by eshengsky** [comment]
bower是全局安装。请检查项目根目录下是否有.bowerrc文件、public下是否有libs目录。

**Comment by zhengzhiqiang** [comment]
项目下有.bowerrc文件，但是有public/libs目录。
npm install和bower install都执行过了，也没报错，但是访问的时候提示Failed to load resource: the server responded with a status of 404 (Not Found)

另外，怎么修改3000的监听端口呢？新手不懂哈，帮忙指导下。我要绑定到自己的域名下

**Comment by eshengsky** [comment]
404问题请自行排查，改变监听端口可以通过修改环境变量PORT，或者修改 bin/www 文件。
请善用搜索引擎...

**Comment by zhengzhiqiang** [comment]
已经完全按照你的步骤来了，不懂是不是README中漏了什么细节问题呢？
