### ISSUE TITLE
请问下二级目录要怎么生成？

### ISSUE THREAD

**Issue by zhengzhiqiang** [eshengsky/iBlog#11]
你好，很感谢您的共享和帮助，博客我已经搭建起来了。目前遇到了一个问题，就是不知道用编辑器怎么直接生成每篇博客的一级、二级目录，每次要做只能是切换到code模式，然后copy  html代码过去修改。但是这样很麻烦，而且我二级目录还出现不了。问下有什么其他简单的方式吗？谢谢

**Comment by eshengsky** [comment]
1级目录请选择编辑器工具条中"段落格式"的"标题2"，2级目录请选择"标题3"。这2中标题格式会自动帮你加上对应样式的。
