### ISSUE TITLE
文章Alias唯一？

### ISSUE THREAD

**Issue by ghost** [eshengsky/iBlog#19]
hi / 你好，
    你能讲一下为什么文章的Alias也是唯一的？ 不是已经有_id作为唯一键了吗？

**Comment by eshengsky** [comment]
@StarXY 
因为iBlog2将文章Alias用作文章URL的一部分，如：
http://www.skysun.name/blog/javascript/javascript-declaration-hoisting
以使URL具备良好的可读性。
所以Alias必须唯一，否则无法唯一匹配文章数据。
