### ISSUE TITLE
有几个小bug

### ISSUE THREAD

**Issue by xrian** [eshengsky/iBlog#20]
谢谢博主提供的源码,我花了半天时间也搭建了一个.^_^
搭建的过程中,发现有几个小问题,还望你有时间更新下代码.
一.我将代码下载下来,即使我选择的是中文界面,但是文章分类那里,全部分类和未分类,显示的也是英文字体.
二,发布文章后,后台管理界面,发布时间是24小时制的,查看文章详情时,发布时间是12小时制的.(不知道这12小时是不是故意设置的).
三.关于管理界面,上传头像时,返回的图片路径有问题,我服务器用了nginx转发到3000端口,返回的路径是http://localhost:3000/images/QQ%E6%88%AA%E5%9B%BE20170709172910.png.导致图片找不到.
不过,保存后显示的图片是正常的啦.
上面几个问题其实都无关大雅啦,不影响功能使用,并且用起来确实感觉蛮不错的,谢谢博主开源的代码

**Comment by xrian** [comment]
第一个问题,我将i18n.js中的defaultLocale改为zh-CN就显示正常了,但是这样带来个问题,中英文切换好像有问题.不过我没有用到英文界面,直接将切换按钮屏蔽了.
第二个问题.route-->blog.js中253行YYYY-MM-DD hh:mm改为YYYY-MM-DD HH:mm,大写的HH代表24小时,小写的代表12小时
第三个问题,我看了下,发现图片上传那有点看不懂,就没去找了-.-

**Comment by xrian** [comment]
百度翻译的APP ID在newarticle.js里写死了,没有做成配置化,我还在想为什么百度翻译只能填个key.
这个可以在readme.md中说明一下

**Comment by eshengsky** [comment]
@xrian 谢谢你的问题^_^ 但我最近非常忙，我会在闲下来后处理一下~

**Comment by xrian** [comment]
嗯,其实都是些小bug,不要紧啦.有时间再弄

**Comment by eshengsky** [comment]
畅言好像不支持在本地启用留言功能。

**Comment by xrian** [comment]
这样啊,好的,我明天升级到服务器上去试试😆

**Comment by jsochen** [comment]
畅言的conf怎么找  或者怎么设置
