### ISSUE TITLE
redis的密码如何设置

### ISSUE THREAD

**Issue by Cuihongsen** [eshengsky/iBlog#23]
redis的密码如何设置

**Comment by eshengsky** [comment]
不支持配置，你需要修改下源码：
https://github.com/eshengsky/iBlog2/blob/master/utility/redisClient.js#L7

传入 `createClient` 函数的参数改成一个对象：
```js
{
  host: config.Redis.Host || 'localhost',
  port: config.Redis.Port || 6379,
  password: 'your pwd'
}
```
