### ISSUE TITLE
建议使用editor.md替代现有编辑器

### ISSUE THREAD

**Issue by xhb** [eshengsky/iBlog#36]
你好，非常喜欢你的这个博客系统，但是编辑器不是很喜欢，所见即所得编辑过程效率太低，图片处理不完善，在手机上看文章，经常出现文章内的图片不能自动适应的情况。这在使用微信传播，体验很不好。
如果可以改成下面这个编辑器，那就更加完美了。。。。
http://pandao.github.io/editor.md/

**Comment by eshengsky** [comment]
现在已支持所见即所得和markdown两种编辑器可供选择。
