### ISSUE TITLE
\node_modules\.staging 不存在，安装依赖的时候报错

### ISSUE THREAD

**Issue by hxsen** [eshengsky/iBlog#52]
你们是怎么安装的。为什么我执行npm install的这一步都进行不下去的呢？

`
npm WARN tar ENOENT: no such file or directory, open 'G:\HOUXIN\node_web\node_modules\.staging\rxjs-b2b51ac7\src\internal\scheduler\VirtualTimeScheduler.ts'
npm WARN tar ENOENT: no such file or directory, lstat 'G:\HOUXIN\node_web\node_modules\.staging\winston-e47eaf85\scratch\1280\node_modules\core-js\library\fn\math'
npm ERR! code ETARGET
npm ERR! notarget No matching version found for event-stream@3.3.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'iblog2'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\houxin\AppData\Roaming\npm-cache\_logs\2019-01-05T07_18_36_041Z-debug.log
`
怎么就我遇到这种问题的，网上查了查都不能解决的额

**Comment by Liaozhenting** [comment]
我是这样做的。
先删除package-lock.json,然后
npm i --save-dev event-stream
然后
npm i

**Comment by eshengsky** [comment]
event-stream 某几个版本被植入了恶意代码，所以找不到相关版本，`npm update` 试试。
