### ISSUE TITLE
nodejs应用线上部署问题

### ISSUE THREAD

**Issue by CarsonYang** [eshengsky/iBlog#6]
你好，你的开源博客很好，让我这个nodejs新手收益良多。但是我现在碰到一个问题，nodejs应用环境，你是在哪个云服务器上做的呀？我现在的阿里云虚拟机，好像部署不了nodejs的应用，很郁闷呀！

**Comment by eshengsky** [comment]
我用的阿里云服务器ECS，是属于独立的主机，所以基本不存在什么约束。云虚拟机就不清楚了，你可以联系阿里客服咨询一下。

**Comment by CarsonYang** [comment]
好的！谢谢！
