### ISSUE TITLE
请问现在编辑器只有markdown模式了吗？

### ISSUE THREAD

**Issue by sekaiamber** [eshengsky/iBlog#80]
因为自己用了很久倒是没问题，但是给长辈开了一个blog以后，发现没有所见即所得的编辑器了。

**Comment by eshengsky** [comment]
是的，v2 版本仅支持 MarkDown 编辑器了，如果要使用所见即所得模式的编辑器，可以使用 [v1](https://github.com/eshengsky/iBlog/tree/v1.0.0) 版本。
