### ISSUE TITLE
redis是否可以不依赖？

### ISSUE THREAD

**Issue by zhengzhiqiang** [eshengsky/iBlog#9]
你好，redis是否可以调整为optional的？这样如果服务器资源不是那么多的话，比较节省资源

**Comment by eshengsky** [comment]
可以。但可能最近没有时间更新。欢迎Pull request.

**Comment by eshengsky** [comment]
已更新，Redis现在是可选的了。

**Comment by eshengsky** [comment]
@zhengzhiqiang 已更新，Redis现在是可选的了。
